/* romans*/
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,"Gail Carriger",'POLICIER','',7, 30 ,"Angleterre, début du XIXe siècle. Sophronia, 14 ans, est un défi permanent pour sa mère : elle préfère démonter les horloges et grimper aux arbres plutôt qu'apprendre les bonnes manières ! Mme Temminnick désespère que sa fille devienne jamais une parfaite lady, aussi l'inscrit-elle au Pensionnat de Mlle Géraldine qui s'attache au perfectionnement des jeunes dames de qualité. Très vite, Sophronia comprend que cette école ne correspond pas exactement à l'idée que sa mère s'en faisait. Certes, les jeunes filles y apprennent l'étiquette, mais aussi celui de la diversion, de l'espionnage et de l'acte de donner la mort - tout cela de la manière la plus civilisée possible, bien sûr. C'est une chose d'apprendre à faire une révérence comme il faut, c'en est une autre d'apprendre à la faire en lançant un couteau... ","Etiquette et espionnage",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,"Pierre Bottero",'FANTASY','',7.5, 30 ,"Quand Camille vit le poids lourd qui fonçait droit sur elle, elle se figea au milieu de la chaussée...","D'un monde à l'autre",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,"Eric l'homme",'FANTASY','',10, 30 ,"Guillemot est un garçon du Pays d'Ys, situé à mi-chemin entre le monde réel et le Monde Incertain. Mais d'où lui viennent ses dons pour la sorcellerie que lui enseigne Maître Qadehar ? Et qu'est devenu Le Livre des Etoiles, qui referme le secret de puissants sortilèges ? Dans sa quête de vérité, Guillemot franchira la Porte qui conduit dans le Monde Incertain, peuplé de monstre et d'étranges tribus...","Etiquette et espionnage",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Eoin Colfer','FANTASY','',8.5, 30 ,"Du rififi dans la « fantasy » ! Avec ce premier épisode des aventures d'Artemis Fowl, l'univers des contes de fées prend un sacré coup de neuf. Finies les ambiances médiévales, les royaumes d'en haut ou d'en bas, les héros pleins de bons sentiments et les poudres de perlimpinpin: notre héros (un méchant, ce qui n'est pas banal!), bardé de gadgets techno, évolue dans le monde moderne, traqué par les services spéciaux, à la recherche de fées qu'il enlève et rançonne. Décapant.",'Artemis Fowl - Tome 1 : Artemis Fowl ','ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Christian Grenier','POLICIER','',7.9, 30 ,"L'Omnia 3 est un ordinateur perfectionné. De là à lui imputer les meurtres des six hommes retrouvés devant son moniteur... Chargée de l'enquête, la jeune Logicielle, ainsi surnommée pour ses talents informatiques, découvre que les victimes portaient sur le visage l'expression d'une horrible terreur et utilisaient toutes le très curieux programme LTGP... Les passionnés d'informatique surferont sans problème sur l'intrigue, les amateurs de polars aussi. Le polar informatique que l'on s'arrache est né.","L'ordinatueur",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Christian Grenier','SF','',4.95, 30 ,"« Fahrenheit 451 », le chef-d'oeuvre de Ray Bradbury, inspire encore aujourd'hui de nombreux auteurs de science-fiction. Christian Grenier remet au goût du jour le thème de la destruction des livres et de la chasse aux lecteurs en opposant deux clans : le gouvernement des Lettrés, qui a interdit les écrans, et les Zappeurs, qui ont inventé un virus effaçant les mots !","virus liv3 ou la mort des livres",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Isaac Asimov','SF','',6, 30 ,"Il était un temps où les robots n'étaient qu'automates idiots ou machines se retournant contre leur créateur. Mais Asimov est arrivé, et tout a changé. La vie est belle aujourd'hui pour les robots, ils sont ouvriers, nourrices, explorateurs spatiaux, politiciens, enquêteurs, prophètes même. La liberté à fond les boulons. Presque. Car il y a les Trois Lois de la Robotique, qui pourraient se résumer à : les robots aident les hommes sans jamais les mettre en péril, et s'aident aussi tant que cela ne contrevient pas à l'énoncé précédent. Le Cycle des Robots est un ensemble de nouvelles et de romans où hommes et robots s'évertuent à faire appliquer ces lois, à les contourner, à les prendre en défaut. Et la palette imaginative de l'auteur ne connaît jamais de baisse de tension ! Suivez donc les cas de conscience du cerveau positronique, les leçons de la logique robotique et les souvenirs de Susan Calvin, la première robopsychologue.","Le cycle des robots - Tome 1 : Les robots ",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Isaac Asimov','SF','',5.6, 30 ,"Comment risque de réagir un robot programmé pour un environnement lunaire dès lors qu'il se retrouve égaré sur Terre ? Un robot peut-il mentir à un procès pour préserver les intérêts de son utilisateur ? Le docteur Susan Calvin, robopsychologue, dialogue avec les androïdes pour faire la lumière sur ces étranges affaires. Et découvre davantage de défauts de programmation chez l'homme que chez ses fidèles créations...","Le cycle des robots - Tome 2 : Un défilé de robots ",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'M.P. Armand','DRAMATIQUE','',7.4, 30 ,"Constance sort à peine de l'enfance lorsque son existence bascule brutalement dans l'horreur. Hier encore, elle jouait dans la «courée» de son immeuble. À quatorze ans, elle se retrouve orpheline et doit entrer en usine. Dès lors, chaque matin, elle sera réveillée à cinq heures par les cloches de la fabrique. Chaque soir, elle ressortira abrutie par le vacarme des métiers. Pour échapper à ce cauchemar, elle épouse Bart, un ouvrier belge. Trouvera-t-elle enfin auprès de lui le bonheur qui lui a toujours été refusé ?La suite de l'histoire, c'est Charlotte, sa fille aînée, qui nous la raconte. Ainsi se poursuit le voyage dans ce Nord de la fin du XIXe siècle qu'éclairent l'amitié, le courage et l'espoir.Un grand roman qui donne enfin une parole digne d'eux à ces gens du peuple qui, en leur temps, n'avaient guère le droit de la prendre.",'La couree','ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'M.P. Armand','DRAMATIQUE','',6.3, 30 ,"En 1900, Louise est une enfant insouciante et joyeuse. Confiante, elle regarde le siècle nouveau s avancer à grand pas. On le voudrait riche de «promesse et d espoir», mais les conditions de travail des ouvriers sont toujours difficiles…En 1912, Louise s éprend de Mathieu, un bel instituteur qui l emmène vivre près de Tourcoing. Benoît nait en 1914, un peu avant l été. toute à son amour, Louise n a guère prêté attention aux événements qui ébranlent le monde… La guerre éclate. Le Nord est occupé. La désolation, la famine, la peur s installent. Un courrier cruel annonce la mort de Mathieu. Effondrée, Louise perd courage. Mais, pour Benoît, elle fait semblant de vivre. Pourra-t-elle un jour retrouver le bonheur ?Le second volet de la trilogie que Marie-Paul Armand dédie à la région du nord…Une fresque bouleversante !","Louise - la couree,2 Tome 2",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'M.P. Armand','DRAMATIQUE','',6.3, 30 ,"Benoît, le fils de Louis, réalise son rêve d'enfant. Il rejoint la grande famille des cheminots et conduit la Pacific 231, locomotive légendaire, véritable monstre d'acier.Mais le monde perd son équilibre précaire.La crise économique se durcit. Le nazisme monte. La guerre éclate. Les années noires commencent : après l'exode et la débâcle, l'Occupation et ses cohortes d'horreur… Courageusement, Benoît, Louise et son mari résistent à l'ennemi, et font passer en zone libre nombre de leurs concitoyens.Mais dans un temps où les bons et les méchants ne font parfois qu'un, la discorde ne va-t-elle pas aussi envenimer la vie de cette famille française ballottée par le destin ?Ainsi s'achève "La courée", la magnifique fresque de Marie-Paul Armand dédiée à cette région chère à son cœur : le Nord.Le troisième volet de la trilogie que Marie-Paul Armand dédie à la région du Nord.",'Benoit - la couree,3 Tome 3','ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Åsa Larsson','HORREUR','',24.26, 30 ,"Rebecka Martinsson, avocate fiscaliste à Stockholm, reçoit un matin un coup de téléphone affolé de Sanna Strandgard, son amie d'enfance à Kiruna en Laponie, lui annonçant la mort de son frère Viktor, retrouvé sauvagement assassiné au coeur de l'église où il officiait. Viktor Strandgard, c'est un peu le Messie suédois : après un coma prolongé, l'homme avait écrit un livre sur son aller-retour dans le monde des morts et contribué activement à la création d'une église à Kiruna dont les disciples n'ont cessé de croître avec les années. Quand Rebecka apprend que Sanna, qui a découvert le corps, est considérée comme la suspecte n° 1, elle n'hésite pas à retourner dans le village de son enfance. Mais, dans la petite ville, son arrivée ne fait pas que des heureux. Les trois pasteurs de l'église semblent avoir beaucoup de choses à cacher et la neige ne va pas tarder à se teindre de sang...",'Horreur boréale','ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'R.L. Stine','HORREUR','',5.9, 30 ,"","Le château de l'horreur - L'école des zombies Tome 04 : Le château de l'horreur ",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'R.L. Stine','HORREUR','',5.9, 30 ," Fan de magie, Steven adore se donner en spectacle devant tout le collège ! Il aime aussi faire apparaître des pièces de monnaie dans les oreilles de ses copines Ava et Courtney, ce qui les agace profondément. Les deux filles décident alors de lui jouer un tour. Elles remplacent l'eau du gobelet qu'il doit boire sur scène par une boisson imbuvable non identifiée. Le jour J, le pauvre Steven rentre chez lui en catastrophe. Et, par un mystérieux tour de passe-passe, le voilà qui rétrécit en quelques minutes et prend la taille d'une poupée Barbie...","Le château de l'horreur - La nuit des créatures géantes Tome 02 : Le château de l'horreur ",'ROMAN');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Christian Grenier','POLICIER','',7.9, 30 ,"Lorsque le rideau se lève sur l’actrice étendue à terre, un poignard dans le dos,le public croit que le meurtre fait partie de la mise en scène. Mais Matilda a bel et bien été assassinée… L’inspecteur Germain et sa jeune stagiaire Logicielle se lancent dans une enquête fertile en coups de théâtre. Ils ont pour décor le Théâtre du crime et pour suspects les différents protagonistes de la pièce, de l’auteur aux machinistes…",'Coups de théâtre','ROMAN');




/* mangas */
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Natsuki Takaya','ROMANCE','',6.99, 30 ,"Tohru, mignonne et courageuse lycéenne, vivait sous une tente, dans les bois. Recueillie pour ses talents en matière de travaux ménagers par la famille de Yuki Soma, un de ses camarades de classe, Tohru vit maintenant entrourée de garçons dans une grande maison. Mais ce qu'elle ignore, c'est que la famille Soma est victime d'une malédiction cachée. Certains de ses membres se tranforment, dans des circonstances particulières, en un des douze animaux du zodiaque chinois ! Avec d'aussi étranges personnages, la nouvelle vie de Tohru va lui réserver de nombreuses surprises.",'Fruits Basket, tome 1','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'CLAMP','FANTASY','',7, 30 ,"Dans le pays de Clow, vivent Shaolan et Sakura, qui s'aiment secrètement malgré leurs différences sociales. Un jour, survient la catastrophe, lors d'une attaque ennemie sur le pays : Sakura perd sa mémoire pour des raisons mystérieuses ! ",'Tsubasa Reservoir Chronicle, tome 1','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Tsukasa Hojo','POLICIER','',8.5, 30 ,"",'City Hunter, tome 12','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Kazuo Maekawa (Dessinateur), Kenji Kuroda (Scénario)','POLICIER','',7, 30 ,"Benjamin Hunter et son inénarrable inspecteur Tektiv, toujours fidèle au poste, se retrouvent coincés en pleine campagne et vont dormir dans un hôtel chic des environs. Mais c'est un établissement bien étrange que cette ancienne bâtisse cachée dans ces montagnes qu'on dit refuge de démons du folklore local. Démons qui auraient potentiellement commis un meurtre, provoqué des incendies et fait disparaître le mari d'une jolie femme. Le mystère est total dans ce huis clos à l'échelle de tout un bâtiment de l'hôtel, qui révélera bien des secrets cachés dans ses murs. Dans l'affaire suivante, Hunter et Tektiv se retrouvent confrontés à une curieuse énigme médicale. Mais quel lourd secret gangrène la clinique Guéridon ? Malgré le talent de son directeur, elle semble condamnée à une fermeture prochaine. D'autant qu'un patient est retrouvé assassiné dans une salle d'attente apparemment fermée ! Le coupable ferait-il partie du personnel soignant ou des malades ?Kazuo Maekawa (illustrateur) et Kenji Kuroda (auteur) ont collaboré sur les adaptations des célèbres jeux video Phoenix Wright : Ace Attorney et Ace Attorney Investigations publié chez Kodansha. Auparavant, le mangaka Kazuo Maekawa avait déjà publié Shurabaka! (2006) et Yayabusu (2004). En 1966, il gagne le prix Shogakukan avec Baki-chan to Ganta.",'Ace attorney investigations - Tome 4 : Ace attorney investigations','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Kazuo Maekawa (Dessinateur), Kenji Kuroda (Scénario)','POLICIER','',21.39, 30 ,"Après Phoenix Wright, ce sont cette fois les aventures de son illustre rival Benjamin Hunter qui arrive en manga ! Retrouvez-le accompagné du fidèle Inspecteur Tektiv dans des histoires entièrement inédites : le mystère d'un cadavre retrouvé au bal costumé, et un chanteur de groupe de rock qui apparaît sur scène assassiné, de manière inexplicable !Kazuo Maekawa (illustrateur) et Kenji Kuroda (auteur) ont collaboré sur les adaptations des célèbres jeux video Phoenix Wright : Ace Attorney et Ace Attorney Investigations publié chez Kodansha. Auparavant, le mangaka Kazuo Maekawa avait déjà publié Shurabaka! (2006) et Yayabusu (2004). En 1966, il gagne le prix Shogakukan avec Baki-chan to Ganta.",'Ace attorney investigations - Tome 1 : Ace attorney investigations ','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Natsuki Takaya','ROMANCE','',6.99, 30 ,"Avez-vous déjà entendu parler de la triste histoire de l'exclusion du chat des douze signes du zodiaque chinois et cela à cause de la fourberie du rat ? Torou Honda la connaît depuis toujours. Aujourd'hui, Torou l'orpheline a seize ans et a choisi de vivre de manière totalement indépendante dans une grande tente au milieu d'un terrain en friche. Mais ce terrain appartient à la famille voisine Sôma. En fait, tous les membres de la famille Sôma ont été maudits et se transforment en l'un des douze animaux du zodiaque chinois (plus le chat !) à chaque fois qu'ils sont trop fatigués, ou qu'ils sont approchés de trop près par une personne à percer leur secret sans l'avoir magiquement oublié. Après mûres réflexions, les Sôma permettent donc à Torou de vivre chez eux. Mais la cohabitation ne sera pas de tout repos. ",' Fruits basket - Tome 2 Tome 02 : Fruits Basket ','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Ai Yazawa','ROMANCE','',6.95, 30 ,"Deux jeunes filles japonaises ont en commun leur prénom "Nana", leur âge et leur attirance pour Tokyo. La première, étudiante rêveuse et tête en l'air, est à la recherche du prince charmant. Quant à l'autre, plus déterminée et solitaire, c'est grâce à son premier amour qu'elle est devenue chanteuse dans un groupe de rock amateur.",'Nana - Tome 1','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Hiro Mashima','FANTASY','',6.95, 30 ,"Les guildes magiques sont des associations. Elles proposent différentes tâches aux magiciens, allant de la recherche d'un objet à l'attaque en règle. Lucy, une jeune fille, rêve de devenir magicienne. Un jour, elle rencontre Natsu, un magicien maîtrisant le feu, ce dernier l'invite alors à rejoindre sa guilde. Il s'agit de la célèbre Fairy Tail, le sujet de tous les rêves de Lucy. Mais celle-ci est bien mystérieuse et semble être à l'origine de nombreux scandales.",'Fairy Tail - Tome 01','MANGA');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Hiro Mashima','FANTASY','',7, 30 ,"Dans l'univers des guildes de magiciens, une seule rassemble les éléments les plus incontrôlables, la Fairy Tail ! Dans celle-ci, on retrouve, Natsu le manipulateur du feu, Happy le chat, Grey le magicien exhibitionniste, Loki le séducteur et Kanna l'alcoolique... Lucy, la constellationniste, débute... Pour sa première mission, elle fait équipe avec Natsu et Happy. Le client serait... un voleur ?!",'Fairy Tail - Tome 02','MANGA');


/* manuels */
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Véronique Babin','EDUCATIF','',11.5, 30 ,"Une encyclopédie pour les 3/6 ans. Découvrir le monde de tous les jours, la nature et le monde plus lointain. Comprendre son corps, le mouvement du temps. S'ouvrir à tout ce qui bouge autour de soi. Un livre pour demain, à lire dès aujourd'hui.",'MEGA Poussin','MANUEL');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Richard Lassaigne, Michel de Rougemont','INFORMATIQUE','',21.9, 30 ,"Cet ouvrage présente les principaux domaines de la logique qui contribuent aux fondements de l'informatique. Il est issu de plusieurs enseignements en mathématiques et informatique. Le premier tome est consacré à la logique du 1er ordre, la calculabilité et les fonctions récursives, le lambda-calcul et les systèmes de type pour les langages fonctionnels. Le second tome traitera de la définissabilité et de la théorie de la complexité. Il s'adresse aux étudiants de 2e et 3e cycles, ainsi qu'aux élèves ingénieurs intéressés par les liens nécessaires entre la logique et l'informatique. Des exercices placés en fin de chapitre facilitent l'évaluation des acquis. Dès lors cet ouvrage représente un véritable outil tant pratique que théorique.","Logique et fondements de l'informatique",'MANUEL');

/* BDs */
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Didier Conrad (Dessinateur), Jean-Yves Ferri (Scénario)','ANY','',7, 30 , "Les personnages créés par les deux génies du 9e art Albert Uderzo et René Goscinny sont de retour ! Après Astérix chez les Pictes et Le Papyrus de César, Astérix et Obélix reviennent dans Astérix et la Transitalique, le nouvel album signé par les talentueux Jean-Yves Ferri et Didier Conrad. N'en déplaise à Obélix, les Italiques, les habitants de l'Italie, ne sont pas tous des Romains, au contraire ! Les Italiques tiennent à préserver leur autonomie et voient d'un mauvais oeil les velléités de domination de Jules César et ses légions. Dans Astérix et la Transitalique, nos héros favoris s'engagent dans une aventure palpitante à la découverte de cette surprenante Italie antique !",'Astérix - Tome 37 : Astérix et la Transitalique','BD');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Patrick Sobral (Scénario), Patrick Sobral (Dessinateur)','ANY','',10.95, 30 ,"C'est un grand jour à Orchidia ! Des quatre coins d'Alysia, les grands de ce monde sont venus assister à l'épreuve du bâtonaigle de Jadilyna qui désignera la princesse Shun-Day comme reine du royaume à la place de sa tante, l'impitoyable Invidia. Mais dans l'ombre de cet événement se trame une sombre machination qui pourrait bien finir en tragédie. Mais qui est visé par cet infâme complot ?",'tLes Légendaires - World Without : Le Royaume des larmes Tome 20 : Les Légendairesitre','BD');
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Christophe Arleston (Scénario), Didier Tarquin (Dessinateur)','ANY','',8.5, 30 ,"Au Castel Or-Azur la fête bat son plein mais Lanfeust n'est pas d'humeur à fêter quoique ce soit. Si ses armées sont en déroute, Lilth court toujours et il ne faut pas lui laisser le temps de reprendre des forces sinon tout serait à refaire. Il souhaite rassembler ses fidèles compagnons et partir à sa recherche au plus vite. Mais la déesse, dont la duplicité n'est plus à prouver, n'est pas si loin...",'Lanfeust Odyssey - Tome 9 : Le stratège ingénu','BD');

/* Essais */
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Laurent Alexandre','PHYLOSOPHIE','',20.9, 30 ,"L’intelligence artificielle peut elle dépasser les humains, et comment l’éducation doit faire sa révolution. \nDepuis la parution en 2011 de son premier essai La mort de la mort, comment la technomédecine va bouleverser l’humanité, Laurent Alexandre s’est révélé comme l’un des plus visionnaires analystes des révolutions technologiques.\n Il s’attaque aujourd’hui à l’Intelligence artificielle (IA) et aux vertigineuses mutations qu’elle va déclencher dans nos modes de vie, et en particulier dans notre conception de l’éducation. \n D’un côté, l’IA progresse bien plus vite que tous les pronostics avancés  : la rapidité d’apprentissage de l’IA est multipliée par 100 chaque année. Il faut trente ans pour former un ingénieur ou un radiologue, quelques heures pour éduquer une IA !\n De l’autre, une école qui n’a pas évolué depuis 250 ans qui forme aux métiers d’hier et qui n’a pas intégré le bouleversement inévitable que l’IA va provoquer sur le marché du travail. Comment faire pour que nos cerveaux biologiques résistent à l’IA et restent complémentaires  ? Comment nos enfants pourront-ils rester compétitifs face à l’IA  ? Comment l’éducation, non totalement darwinienne, trouvera-t-elle sa place à côté des cerveaux de silicium boostés par les moyens presque infinis des GAFA et autres géants américains et chinois  ?\n Quels scénarios l’Humanité devra-t-elle choisir  ? Faut-il accepter le vertige transhumaniste qui nous «  upgrade  » biologiquement mais nous maintient Homme  ? Fusionner avec l’IA en devenant des cyborgs  ? Interdire ou limiter puissamment l’IA ? \nC’est à cette réflexion fondamentale et passionnante que Laurent Alexandre nous invite.",'La guerre des intelligences','ESSAI');      
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Erik Orsenna','BIOGRAPHIE','',10.95, 30 ,"Depuis l’enfance, il est notre ami. Et les animaux de ses Fables, notre famille. Agneau, corbeau, loup, mouche, grenouille, écrevisse ne nous ont plus jamais quittés.Malicieuse et sage compagnie !Mais que savons-nous de La Fontaine, sans doute le plus grand poète de notre langue française ?Voici une promenade au pays vrai d’un certain tout petit Jean, né le 8 juillet 1621, dans la bonne ville de Château-Thierry, juste à l’entrée de la Champagne. Bientôt voici Paris, joyeux Quartier latin et bons camarades : Boileau, Molière, Racine.Voici un protecteur, un trop brillant surintendant des Finances, bientôt emprisonné. On ne fait pas sans risque de l’ombre au Roi Soleil.Voici un très cohérent mari : vite cocu et tranquille de l’être, pourvu qu’on le laisse courir à sa guise.Voici la pauvreté, malgré l’immense succès des Fables.Et, peut-être pour le meilleur, voici des Contes. L’Éducation nationale, qui n’aime pas rougir, interdisait de nous les apprendre. On y rencontre trop de dames « gentilles de corsage ».Vous allez voir comme La Fontaine ressemble à la vie : mi-fable, mi-conte.Gravement coquine.",'La Fontaine Une école buissonnière','ESSAI');      
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,"Jean d'Ormesson",'BIOGRAPHIE','',19.89, 30 ,"La gloire plaît aux femmes et les fascine comme le pouvoir. Chateaubriand - sans doute le plus grand écrivain français - lia plus que personne sa vie sentimentale à sa vie politique et littéraire. L'indifférence et la passion qui flottaient autour de lui faisaient se lever sur ses pas des bataillons de jeunes femmes, armées et casquées pour les combats de l'amour. A chacune il fut tenté de murmurer Mon dernier rêve sera pour vous. A une seule, avant sa mort, il dira ces quelques mots qui unissent aux yeux de l'histoire deux destins d'exception.La première biographie de jean d'Ormesson : le portrait d'un séducteur par un écrivain - et peut-être aussi l'inverse.Ce gros livre tient du mémoire, du feuilleton, de la chronique historique la plus sérieuse et du roman le plus brillant.Annie Coppermann",'Mon dernier rêve sera pour vous','ESSAI');      

/* Magazine */
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Collectif','HISTOIRE','',5.9, 30 ,"La vie de la population parisienne, l'organisation de la ville, les transports ou encore les métiers qui y étaient exercés. L'histoire de la cité retracée à travers les bâtiments toujours présents : places, fastueux hôtels particuliers du centre et habitats insalubres et surpeuplés des faubourgs.",'Paris au temps des grands rois','MAGAZINE');      
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Collectif','ART','',9.5, 30 ,"",'André Derain, la décennie radicale','MAGAZINE');      
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Collectif','LOISIR','',6.95, 30 ,"Retrouvez toutes les informations sur l'univers de \"Walking Dead\" dans un magazine qui vous fera découvrir les coulisses de la série comics comme ceux de la série télévisée.",'Walking Dead Comics - Tome 20 : Walking Dead magazine','MAGAZINE');      
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Collectif','ART','',9, 30 ,"A l'occasion de l'exposition consacrée à la collection de pastels du Petit Palais, l'ouvrage offre un panorama des principaux courants artistiques de la seconde moitié du XIXe siècle, de l'impressionnisme au symbolisme, dont les fleurons sont constitués par les oeuvres de Berthe Morisot, Auguste Renoir, Paul Gauguin, Odilon Redon. Avec un point sur la technique et la conservation des pastels.","Lart du pastel de Degas à Redon",'MAGAZINE');      




/* roman        
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'auteur','genre','',7, 30 ,"summary",'titre','ROMAN');
 manga
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'auteur','genre','',7, 30 ,"summary",'titre','MANGA');
-- manuel
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'auteur','genre','',7, 30 ,"summary",'titre','MANUEL');
-- BD
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'auteur','ANY','',7, 30 ,"summary",'titre','BD');
-- ESSAI
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'auteur','genre','',7, 30 ,"summary",'titre','ESSAI');      
-- MAGAZINE
INSERT INTO Book(idBook, author, genre, picture, price, stock, summary, title, type) VALUES (1,'Collectif','genre','',7, 30 ,"summary",'titre','MAGAZINE');      
*/